### ISSUE TITLE
Missing sound file

### ISSUE THREAD

**Issue by danshev** [flomio/flomio-sdk-ios#2]
Just FYI, I get this when attempting to build the Swift example:

`error: /Users/scottcondron/Developer/flomio_mw_releases/FlomioSDK/Assets/ScanSound.caf: No such file or directory`

**Comment by danshev** [comment]
I think the issue might be bigger, though ... removed the reference and builds are still going haywire.

**Comment by danshev** [comment]
<img width="1280" alt="screen shot 2018-03-11 at 12 49 27 pm" src="https://user-images.githubusercontent.com/3915359/37255970-be583980-252a-11e8-821d-b3ec6d48b3af.png">

**Comment by scottire** [comment]
Are you still seeing this after https://github.com/flomio/flomio_mw_releases/issues/3 was resolved?

**Comment by danshev** [comment]
Nope -- might want to just add notes in your `Readme` for both these issues, that is:

- Podfile can't include `use_frameworks!`
- Need to run `pod install` on the downloaded example project

Thank you for your help!

**Comment by danshev** [comment]
Oops ... I guess the second one is already there 😁

**Comment by scottire** [comment]
👍 Thanks for your suggestion. I will add "Podfile can't include `use_frameworks!`".
