### ISSUE TITLE
_OBJC_CLASS_$_FmSessionManager error

### ISSUE THREAD

**Issue by danshev** [flomio/flomio-sdk-ios#3]
1.  Created a brand new project
2.  Added `pod 'FlomioSDK'` to Podfile, installed, etc.
3.  Added `import FlomioSDK` in ViewController.swift

--- at this point, the project will build ---

4.  Add `var flomioMW: FmSessionManager = FmSessionManager()` ==> project no longer builds

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FmSessionManager", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by danshev** [comment]
For what it's worth, here are the `Other Linker Flags` settings prescribed in [Flomio's _manual_ iOS integration steps](https://docs.flomio.com/#ios-integration):

- `-lc++`
- `-ObjC`

If you use the FlomioSDK pod, here's what is setup for you:
![image](https://user-images.githubusercontent.com/3915359/37255716-bc6c6122-2526-11e8-9699-664d746f5adc.png)

Is there maybe a typo on the `-lc++`?

**Comment by scottire** [comment]
Hi @danshev, 
I am looking into this now. Can you confirm for sanity that you have cloned this repo, ran `pod install` in either example directory, opened the xcworkspace files and ran the project.
Also, can you paste your `Podfile` below?

**Comment by danshev** [comment]
Negative.

I hit errors when I was either:

- Cloning/downloading the project and simply opening the xcodeproj Swift example, or

- Creating my own, new Xcode project (in another, fresh directory) and brining the FlomioSDK into via CocoaPods.

I'll try the first again, this time doing Pod install in the cloned directory.

Just as a note, I'm able to get a blank, new project working by following the old (e.g., drag/drop the iOS folder, etc.) Instructions.

**Comment by scottire** [comment]
Cool, that should work for you to get an example project working without build steps.

As for..
> Creating my own, new Xcode project (in another, fresh directory) and brining the FlomioSDK into via CocoaPods.

Can you paste the contents of the `Podfile` here so we can get that working for you?

**Comment by danshev** [comment]
```
platform :ios, '11.0'

target 'TestBLE' do

  use_frameworks!

  # Pods for TestBLE
  pod 'FlomioSDK'

  target 'TestBLE' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestBLE' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

**Comment by scottire** [comment]
Remove `use_frameworks!` and run `Pod install` again.

**Comment by danshev** [comment]
Yep, that did the trick.

Unfortunately, I often use pods that require `use_frameworks!` (e.g., [AlamoFire](https://github.com/Alamofire/Alamofire)) ... what should I do when I need to use both?  I suppose I might be stuck with the laborious method ...

**Comment by scottire** [comment]
[Unfortunately, it's not possible at the moment. :(](https://github.com/CocoaPods/CocoaPods/issues/3839)

I will close this for now, and reopen and update it if we move to support `use_frameworks!`.

**Comment by olcayertas** [comment]
Not supporting use_frameworks! is a bummer.

**Comment by scottire** [comment]
I've added support for `use_frameworks!` in 3.0.0.
