### ISSUE TITLE
Both example apps (swift & objC) are crashing when kFlojackMsr is configured

### ISSUE THREAD

**Issue by alexmanzer** [flomio/flomio-sdk-ios#4]
I'd like to test the SDK with the provided swift and ObjC examples.

But both apps are crashing (from inside the SDK, not the ViewController) when the device kFlojackMsr is configured.

To reproduce:
```
let defaultConfiguration: FmConfiguration = FmConfiguration()
defaultConfiguration.deviceType = DeviceType.kFlojackMsr
```

will cause this crash:
```
2018-03-21 12:16:08.584028+0100 FlomioSDK_Example[5458:1214660] In Init
*** -[NSURL initFileURLWithPath:]: nil string parameter
(null)
2018-03-21 12:16:08.584132+0100 FlomioSDK_Example[5458:1214660] bundle(null)
```

Please fix the problem or give advice how to use the SDK with the kFlojackMsr.
Thanks in advance.

**Comment by scottire** [comment]
Hi Alex,

Are you using Carthage or Cocoapods, if cocoapods, have you done the steps in the readme?
If you follow the readme in the release from here, there should be no issue: [FlomioSDK](https://www.dropbox.com/s/jo3g50rtmkde53v/FlomioSDK.zip?dl=1).

Scott

**Comment by alexmanzer** [comment]
Yes, i use cocoapods, but the problem was the missing assets (images and the sound file) in the "copy bundle resources" step of the main application. Thanks for pointing me to the FAQs in the readme
