### ISSUE TITLE
[NSURL initFileURLWithPath:] NSInvalidArgumentException

### ISSUE THREAD

**Issue by olcayertas** [flomio/flomio-sdk-ios#5]
I am trying to use `FloJack ACR35-A1` with following code but it makes my application crash:

```
let configuration: FmConfiguration = FmConfiguration();
configuration.deviceType = .kFlojackMsr;
configuration.transmitPower = .highPower;
configuration.scanSound = true;
configuration.scanPeriod = 1000;
configuration.powerOperation = .autoPollingControl;
configuration.allowMultiConnect = false;
manager = FmSessionManager(configuration: configuration);
manager.delegate = GHSessionManagerDelegate(manager);
```
Here is the crash log:

```
In Init
bundle(null)
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'
*** First throw call stack:
(0x185e27164 0x185070528 0x185e270ac 0x18677025c 0x1867701c8 0x10361fb40 0x10361f3e8 0x10454128c 0x104541fac 0x10361f328 0x103638d98 0x103637908 0x1036330f8 0x1045412cc 0x10454128c 0x104545ea0 0x185dcf344 0x185dccf20 0x185cecc58 0x187b98f84 0x18f4455c4 0x1009d62a8 0x18580c56c)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
I am using Xcode Version 9.3 (9E145) with iOS 11.3 on my iPhone.

**Comment by scottire** [comment]
Hi olcayertas,
I will make sure this is resolved for the next push, for the moment make sure Cocoapods is adding ScanSound.caf to your resource bundle. If not, you can drag and drop it in yourself. Internally we are using that audiofile with Apples AVAudioPlayer like this
`[[AVAudioPlayer alloc] initWithContentsOfURL:[NSURL fileURLWithPath:[[NSBundle mainBundle] pathForResource:@"ScanSound" ofType:@"caf"]] error:NULL];`

**Comment by olcayertas** [comment]
I had an issue with `CocoaPods`, I have used `Swift` and I am using `use_frameworks!` so I have used `Carthage` instead. When I inspect framework file i can see sound file and images in it.
![screen shot 2018-04-06 at 17 23 37](https://user-images.githubusercontent.com/1506019/38426426-4a513fe2-39bf-11e8-8383-af8240152906.png)

**Comment by scottire** [comment]
Drag the ScanSound.caf file into your project so that it's in your projects main bundle. 
Also, when using `Carthage`, make sure you follow the integration instructions on [our docs.](https://docs.flomio.com/#ios-integration)

**Comment by olcayertas** [comment]
I have added ScanSound.caf file to my project and problem is solved.
