### ISSUE TITLE
FlomioSDK.framework license terms

### ISSUE THREAD

**Issue by omargomez** [flomio/flomio-sdk-ios#6]
Hi guys, thanks for the sample. It's not clear to me though what are the license terms for this SDK. Could you please explain?

**Comment by scottire** [comment]
Hi Omar, 
This framework is free to use, but it requires internet access and a Flomio licensed reader. If you have a reader which is unlicensed (if bought from a different supplier), you can license it [here](https://flomio.com/shop/apps/flomio-sdk-basic-turnkey-oem-support).

If you would like to use it with readers offline, you can buy a Pro license [here](https://flomio.com/shop/apps/flomio-sdk-pro-operate-your-reader-offline/).

Hope that answers your question :)

**Comment by omargomez** [comment]
Thanks Scott, this is exactly what I'm wanted to know.
