### ISSUE TITLE
cocoaPod install question

### ISSUE THREAD

**Issue by Lowellr** [flomio/flomio-sdk-ios#8]
Hi I've been trying to run the FlomioSDK_Example on Xcode 9.2 after running the pod and I get the error:
`framework not found Pods_FlomioSDK_Example`

I do see it as a linked framework under Target>General

I've tried Both the Objective C and Swift example.
Any advice would be most appreciated

**Comment by scottire** [comment]
Have you called `pod install` from within the example app directory?

It seems similar to this issue unrelated to this pod: [framework not found Pods](https://stackoverflow.com/questions/29865899/ld-framework-not-found-pods)

You could also try a fresh install after clearing your DerivedData, I just tried and it worked for me.

**Comment by Lowellr** [comment]
Hi Scott, Thanks for responding. I really appreciate the help.
 Yes I called  `pod install`from inside the directory. I actually tried both the swift and obj-c examples.
I also tried manually adding the SDK but only see FlomioSDK.framework in the GitHub repo not Pods_FlomioSDK_Example.framework 

<img width="680" alt="screen shot 2018-06-14 at 9 02 12 am" src="https://user-images.githubusercontent.com/1217319/41424094-f5ea19b4-6fb1-11e8-81e7-9e9cbb5f9d57.png">


I don't know enough about Pods to know the difference. 

I think next I will just trying building from scratch, unless you have another idea.




 I do also get this error  in terminal when doing the `pod install` `[!] The `FlomioSDK_Example [Debug]` target overrides the `GCC_PREPROCESSOR_DEFINITIONS` build setting defined in `Pods/Target Support Files/Pods-FlomioSDK_Example/Pods-FlomioSDK_Example.debug.xcconfig'. This can lead to problems with the CocoaPods installation` in Xcode

**Comment by scottire** [comment]
I would suggest deleting your DerivedData, calling `pod deintegrate && pod install --verbose`.
I cannot recreate your issue, make sure you have updated cocoapods. 
Also, you shouldn't need to do this but you can try adding the FlomioSDK.framework to `Embedded Binaries`.

**Comment by Lowellr** [comment]
Hi Scott, Thanks for sticking with me. I deleted the DerivedData,  called pod deintegrate, called  pod install --verbose but got the same result.

I then tried starting with a new project, and added the FlomioSDK.framework manually, along with these steps: https://docs.flomio.com/#configure-project-settings. 
Unfortunately I still got the same error.  Framework not found 

<img width="710" alt="screen shot 2018-06-15 at 2 43 09 pm" src="https://user-images.githubusercontent.com/1217319/41490812-9d83483c-70aa-11e8-96a7-9ec47c6917c5.png">
<img width="890" alt="screen shot 2018-06-15 at 2 42 23 pm" src="https://user-images.githubusercontent.com/1217319/41490814-9d9d81de-70aa-11e8-9209-e3eae3cb6b7d.png">

Do you think I should try another version of the SDK? I have no idea why it wouldn't see a manually attached library. I tried 2 different  single view apps with both Swift and Obj-C code bases. I'm hoping I'm just missing something simple. Thanks again for all your suggestions.

**Comment by grundyoso** [comment]
I find it odd that there's no explicit path to the FlomioSDK framework in the exported `PATH` given that it's not a standard framework:

<img width="144" alt="screenshot 2018-06-15 19 27 27" src="https://user-images.githubusercontent.com/876837/41493128-28ebaba4-70d2-11e8-9e9f-6da256746d92.png">

you could brute force it by placing the Flomio SDK framework in the same directory where the MediaPlayer framework is located to see if that gets you building... then circle back to figure out what in your project it messing things up... it could very well be a cocoa pod error from our part that we just haven't seen.

**Comment by Lowellr** [comment]
That's cool idea grundyoso. I moved the SDK framework into the standard directory and still got the error for project that I made from scratch and the one created from the Pod. The Pod project is actually looking for Pods_FlomioSDK ( but I renamed the SDK and manually added it). Still no dice.  So I don't think the Pod is at fault, I think I have something funny going on with my environment? that isn't allowing it to see the SDK, I just don't know what it is. Is there another sample Xcode project I can download and try? I can't say enough how much I appreciate your help.

**Comment by scottire** [comment]
There is no other example projects you can try unfortunately. 
Xcode can be very fussy about project build settings and linked libraries so sometimes theses issues can be a real pain! 
A few suggestions because it is very difficult to suggest a one size fits all for this problem:
Have you tried adding the FlomioSDK.framework to Embedded Libraries? 
Have you edited anything from the Podfile? 
Make sure you are opening and building from the .xcworkspace file rather than the .xcodeproj file.

**Comment by Lowellr** [comment]
Thanks Scott.  I finally got it to work. You reminded me about  using the .xcworkspace vs. .xcodeproj file.

I think the first time I built the program I used the .xcodeproj  file  ( and even though later I used the  .xcworkspace it messed things up pretty good). I started over cleared all the data, used pod deintegrate && pod install --verbose and made sure I used the .xcworkspace from the start and it built with no errors. Thanks for sticking with me. I'm really so thankful for all your help.

**Comment by grundyoso** [comment]
Awesome! great to hear that. If you'd like to post a positive review of our effort this is the best place to do it: 

https://flomio.com/shop/apps/flomio-sdk-basic-turnkey-oem-support/#reviews

you could also drop stuff on Twitter tagging @flomio ...
